version: '3'

services:
  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ~/mlflow:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    # Add a custom network
    networks:
      - mlflow-network

  training:
    build:
      context: .
      dockerfile: docker/Dockerfile.training
    volumes:
      - ./:/app
      - ~/mlflow:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000  # Use Docker's internal DNS
    depends_on:
      - mlflow
    networks:
      - mlflow-network  # Share the same network

# Define a custom network
networks:
  mlflow-network:
    driver: bridge
