version: '3'

services:
  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    ports:
      - "${MLFLOW_PORT:-5000}:5000"  # Use env variable with fallback
    volumes:
      - ~/mlflow:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    networks:
      - mlflow-network

  training:
    build:
      context: .
      dockerfile: docker/Dockerfile.training
    volumes:
      - ./:/app
      - ~/mlflow:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    networks:
      - mlflow-network

networks:
  mlflow-network:
    driver: bridge
