version: '3'

services:
  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ~/mlflow:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
      - PYTHONPATH=/app  
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns --default-artifact-root file:///mlflow/artifacts

  training:
    build:
      context: .
      dockerfile: docker/Dockerfile.training
    volumes:
      - ./:/app
      - ~/mlflow:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - PYTHONPATH=/app  # Add this line to set the Python path
    depends_on:
      - mlflow
