FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install additional system dependencies for matplotlib/seaborn
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 && apt-get clean

COPY scripts/ /app/scripts/
COPY data/ /app/data/

CMD ["python", "-m", "scripts.model_training"]
